import { NextResponse } from "next/server";
import { writeFile, readFile } from "fs/promises";
import { existsSync } from "fs";
import path from "path";

// Backend directory - 使用相对路径，假设 deepagents 和 deep-agents-ui 在同一目录下
const BACKEND_DIR = process.env.BACKEND_DIR || path.resolve(process.cwd(), "../deepagents");
const CONFIG_FILE = path.join(BACKEND_DIR, "model_config.json");

interface EnabledTools {
  fetch_url?: boolean;
  serpapi_search?: boolean;
  exa_search?: boolean;
  exa_contents?: boolean;
  exa_find_similar?: boolean;
  exa_answer?: boolean;
  exa_research?: boolean;
  tavily_search?: boolean;
  tavily_extract?: boolean;
  tavily_map?: boolean;
  tavily_crawl?: boolean;
  perplexity_search?: boolean;
  perplexity_chat?: boolean;
}

interface ModelConfig {
  provider: string;
  model: string;
  // 通用 API key
  api_key?: string;
  base_url?: string | null;
  // Azure OpenAI 专用字段
  azure_api_key?: string;
  azure_base_url?: string;
  // 其他配置
  model_overrides?: {
    subagents?: { [key: string]: string | null };
    summarization?: string | null;
    suggestions?: string | null;
  } | null;
  serp_api_key?: string;
  exa_api_key?: string;
  tavily_api_key?: string;
  perplexity_api_key?: string;
  enabled_tools?: EnabledTools;
  _last_updated?: string;
  _comment?: string;
}

/**
 * GET /api/backend/config - Read current config
 */
export async function GET() {
  try {
    if (!existsSync(CONFIG_FILE)) {
      return NextResponse.json({
        config: null,
        message: "Config file not found",
        path: CONFIG_FILE,
      });
    }

    const content = await readFile(CONFIG_FILE, "utf-8");
    const config = JSON.parse(content);

    return NextResponse.json({
      config,
      path: CONFIG_FILE,
    });
  } catch (error) {
    console.error("[CONFIG API] Error reading config:", error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/backend/config - Save config to file
 */
export async function POST(request: Request) {
  try {
    const body = await request.json();
    
    // Build config object
    const config: ModelConfig = {
      provider: body.provider || "",
      model: body.model || "",
      _last_updated: new Date().toISOString(),
      _comment: "Auto-generated by frontend. Edit via Settings UI.",
    };

    // 根据 provider 类型设置不同的字段
    if (body.provider === "azure") {
      // Azure OpenAI 使用专用字段
      config.azure_api_key = body.azure_api_key || "";
      config.azure_base_url = body.azure_base_url || "";
    } else {
      // 其他 provider 使用通用字段
      config.api_key = body.api_key || "";
      config.base_url = body.base_url || null;
    }

    // 可选字段
    if (body.model_overrides) {
      config.model_overrides = body.model_overrides;
    }
    if (body.serp_api_key) {
      config.serp_api_key = body.serp_api_key;
    }
    if (body.exa_api_key) {
      config.exa_api_key = body.exa_api_key;
    }
    if (body.tavily_api_key) {
      config.tavily_api_key = body.tavily_api_key;
    }
    if (body.perplexity_api_key) {
      config.perplexity_api_key = body.perplexity_api_key;
    }
    if (body.enabled_tools) {
      config.enabled_tools = body.enabled_tools;
    }

    // Write to file
    await writeFile(CONFIG_FILE, JSON.stringify(config, null, 2), "utf-8");

    console.log(`[CONFIG API] Saved config: provider=${config.provider}, model=${config.model}, path=${CONFIG_FILE}`);

    return NextResponse.json({
      success: true,
      message: "Config saved. Backend will auto-reload.",
      config,
      path: CONFIG_FILE,
    });
  } catch (error) {
    console.error("[CONFIG API] Error saving config:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
